# Generated by Django 4.2.16 on 2024-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="No_of_guests",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="Inventory",
            field=models.IntegerField(),
        ),
    ]
